spring.application.name=user-backend

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://kandid@localhost:3306/kandid
spring.datasource.username=kandid
spring.datasource.password=kandid
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# OpenAPI/Swagger Configuration
springdoc.swagger-ui.path=/docs.html

server.port=8081