spring.application.name=user-backend
# OpenSearch - Shared across environments
os.username=admin
os.password=Kandid@0908
os.hostname=search-meoww-43xw3lvhigkm6jtw3icmires44.ap-south-1.es.amazonaws.com
# Swagger
springdoc.swagger-ui.path=/docs.html
# Default profile
spring.profiles.default=prod
