server.port=8081
# OpenSearch - Shared across environments
os.username=admin
os.password=Kandid@0908
os.hostname=localhost
os.port=9200
os.https=false
# MySQL (Dev)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/kandid
spring.datasource.url=jdbc:mysql://kandid@daataa.cdoq66gy2dsl.ap-south-1.rds.amazonaws.com:3306/kandid
spring.datasource.username=kandid
spring.datasource.password=kandid
# Backend host
backend.url=http://localhost:8081
